

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:11300/eureka/
spring:
  application:
    name: mk-user
feign:
  httpclient:
    connection-timeout: 1000
