

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:11300/eureka/
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: gateway01
          uri: http://localhost:8081/
          predicates:
          - Path=/pro/**
          filters:
            - StripPrefix=1
          -
server:
  port: 12890